import { fileURLToPath, URL } from "node:url";

import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "~": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  test: {
    environment: "jsdom",
    setupFiles: ["./vitest.setup.ts"],
    // Playwright drives a real browser and owns e2e/; vitest must not try to
    // run those specs.
    exclude: ["e2e/**", "node_modules/**", "dist/**", "dist-server/**"],
    coverage: {
      provider: "v8",
      reporter: ["text-summary", "html"],
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        // Generated by the shadcn CLI rather than written here.
        "src/components/ui/**",
        // Thin wrappers: composition is asserted through the routes instead.
        "src/main.tsx",
        "src/routes/router.tsx",
        "src/**/*.test.{ts,tsx}",
        "src/types/**",
      ],
      thresholds: {
        // Highest where correctness is subtle and cheap to pin: the pure
        // normalizers, filter serialization and id encoding.
        "src/lib/**": { lines: 90, functions: 90 },
        "src/api/**": { lines: 85, functions: 85 },
        global: { lines: 70, functions: 70, branches: 70 },
      },
    },
  },
});
